# config/pipelines/hlsdaterange.conf

PIPELINE_INPUT="${PIPELINE_INPUT:-$INPUT_BASE_DIR/hlsdaterange/nodelist}"
PIPELINE_OUTPUT="${PIPELINE_OUTPUT:-$RESULT_BASE_DIR/hlsdaterange/hlsdaterange_${RUN_ID}.txt}"


export PIPELINE_INPUT PIPELINE_OUTPUT
