# config/pipelines/memdecline.conf

PIPELINE_INPUT="${PIPELIINE_INPUT:-$INPUT_BASE_DIR/memdecline/devicelist}"
PIPELINE_OUTPUT="${PIPELINE_OUTPUT:-$RESULT_BASE_DIR/memdecline/memdecline_${RUN_ID}.txt}"
export PIPELIINE_INPUT PIPELINE_OUTPUT
