# config/pipelines/nostream.conf

PIPELINE_INPUT="${PIPELINE_INPUT:-$INPUT_BASE_DIR/nostream/devicelist}"
PIPELINE_OUTPUT="${PIPELINE_OUTPUT:-$RESULT_BASE_DIR/nostream/nostream_${RUN_ID}.txt}"

export PIPELINE_INPUT PIPELINE_OUTPUT
