local oradb_conf="${CONFIG_DIR}/oradbaccess.conf"
[[ -f "$oradb_conf" ]] || {
    log_error "Oracle DB global config file not found: $oradb_conf"
    return 1
}
source "$oradb_conf" 

TARGETDBASSESS_TARGETDATE="${TARGETDBASSESS_TARGETDATE:-"202601010000"}"
TARGETDBASSESS_RECORDSTATUS="${TARGETDBASSESS_RECORDSTATUS:-"-1,3"}"
TARGETDBASSESS_SAMPLEROWS="${TARGETDBASSESS_SAMPLEROWS:-1000}"

export TARGETDBASSESS_TARGETDATE TARGETDBASSESS_RECORDSTATUS TARGETDBASSESS_SAMPLEROWS

if [ -z "${TARGET_DB_IDS+x}" ]; then
    export TARGET_DB_IDS="1 2"
fi

if [ -z "${TARGET_DB_IPS+x}" ]; then
    export TARGET_DB_IPS="xxxx yyyy"
fi

TARGET_DB_PORT="${TARGET_DB_PORT:-0000}"
TARGET_DB_INSTANCE="${TARGET_DB_INSTANCE:-targetdb}"
TARGET_DB_USER="${TARGET_DB_USER:-username}"
TARGET_DB_PASS="${TARGET_DB_PASS:-userpass}"

export TARGET_DB_IPS TARGET_DB_PORT TARGET_DB_INSTANCE TARGET_DB_USER TARGET_DB_PASS

TARGETDBASSESS_ROWSIZE_SQL="${TARGETDBASSESS_ROWSIZE_SQL:-${MODULES_BASE_DIR}/targetdbassess/targetdbassess_rowsize.sql}"
TARGETDBASSESS_TOTALROWS_SQL="${TARGETDBASSESS_TOTALROWS_SQL:-${MODULES_BASE_DIR}/targetdbassess/targetdbassess_totalrows.sql}"
export TARGETDBASSESS_ROWSIZE_SQL TARGETDBASSESS_TOTALROWS_SQL

build_memuserdb_connstring() {
    local db_id="${1:-}"
    read -r -a ARRAY_IPS <<< "${TARGET_DB_IPS}"

    if [[ ! "$db_id" =~ ^[1-${#ARRAY_IPS[@]}]$ ]]; then
        log_err "db_id should be between 1-2"
        return 1
    fi
    local id=$(( $db_id - 1 ))

    conn_str="${TARGET_DB_USER}/${TARGET_DB_PASS}@${ARRAY_IPS[${id}]}:${TARGET_DB_PORT}/${TARGET_DB_INSTANCE}"
    echo "${conn_str}"
}
