# config/oradbaccess.conf 

DB_CLIENT="${DB_CLIENT:-dbclientnode}"
DBACCESS_SSH_OPTS="${DBACCESS_SSH_OPTS:--n -o BatchMode=yes -o ConnectTimeout=10 -q}"
export DB_CLIENT DBACCESS_SSH_OPTS

NLS_DATE_FORMAT="${NLS_DATE_FORMAT:-"YYYY-MM-DD HH24:MI:SS"}"
PARALLEL_DEGREE="${PARALLEL_DEGREE:-4}"
export NLS_DATE_FORMAT PARALLEL_DEGREE
